export const TIME_PERIOD = {
  DAY: 'DAY',
  WEEK: 'WEEK',
  MONTH: 'MONTH',
} as const;

export const GENRE = {
  THEATER: 'THEATER',
  MUSICAL: 'MUSICAL',
  CLASSIC: 'CLASSIC',
  KOREAN_TRADITIONAL_MUSIC: 'KOREAN_TRADITIONAL_MUSIC',
  POPULAR_MUSIC: 'POPULAR_MUSIC',
  DANCE: 'DANCE',
  CONTEMPORARY_DANCE: 'CONTEMPORARY_DANCE',
  CIRCUS_AND_MAGIC: 'CIRCUS_AND_MAGIC',
  MIXED_GENRE: 'MIXED_GENRE',
  KID: 'KID',
  OPEN: 'OPEN',
  ALL: 'ALL',
} as const;

export const AREA = {
  SEOUL: 'SEOUL',
  INCHEON: 'INCHEON',
  DAEJEON: 'DAEJEON',
  DAEGU: 'DAEGU',
  GWANGJU: 'GWANGJU',
  BUSAN: 'BUSAN',
  ULSAN: 'ULSAN',
  SEJONG: 'SEJONG',
  GYEONGGI: 'GYEONGGI',
  CHUNGCHEONG: 'CHUNGCHEONG',
  GYEONGSANG: 'GYEONGSANG',
  JEOLLA: 'JEOLLA',
  GANGWON: 'GANGWON',
  JEJU: 'JEJU',
  UNI: 'UNI',
  ALL: 'ALL',
} as const;

export const SORT_TYPE = {
  TIME: 'TIME',
  VIEWS: 'VIEWS',
} as const;

export const SORT_ORDER = {
  DESC: 'DESC',
  ASC: 'ASC',
} as const;
