export const REGION = {
  '11': '서울특별시',
  '26': '부산광역시',
  '27': '대구광역시',
  '28': '인천광역시',
  '29': '광주광역시',
  '30': '대전광역시',
  '31': '울산광역시',
  '36': '세종특별자치시',
  '41': '경기도',
  '42': '강원도',
  '43': '충청북도',
  '44': '충청남도',
  '45': '전라북도',
  '46': '전라남도',
  '47': '경상북도',
  '48': '경상남도',
  '50': '제주특별자치도',
} as const;

export const REGION_MAP = [
  { caption: '서울특별시', value: '11' },
  { caption: '부산광역시', value: '26' },
  { caption: '대구광역시', value: '27' },
  { caption: '인천광역시', value: '28' },
  { caption: '광주광역시', value: '29' },
  { caption: '대전광역시', value: '30' },
  { caption: '울산광역시', value: '31' },
  { caption: '세종특별자치시', value: '36' },
  { caption: '경기도', value: '41' },
  { caption: '강원도', value: '42' },
  { caption: '충청북도', value: '43' },
  { caption: '충청남도', value: '44' },
  { caption: '전라북도', value: '45' },
  { caption: '전라남도', value: '46' },
  { caption: '경상북도', value: '47' },
  { caption: '경상남도', value: '48' },
  { caption: '제주특별자치도', value: '50' },
];
